venv) sagemaker-user@default:~/f1_ai_mlops_baseline$ python python_scripts/utils/f1ai_model_promoter.py 
Warning: Could not generate AWS temporary credentials. Please make sure you have the necessary permissions.
Promotion response: {'status': 'FAILURE', 'message': "RuntimeError('Failed to get model stage, response=<Response [404]>')"}
(venv) sagemaker-user@d
