
Failed resources:
APP01-NVSGISRSSR36-DEVCDKAUTOMATIONENV | 5:52:14 PM | UPDATE_FAILED        | AWS::CloudFormation::CustomResource | aws-mlops_lambda_layer/aws-mlops_lambda_layer_model_promotion_libraries_custom_resource/Default (awsmlopslambdalayerawsmlopslambdalayermodelpromotionlibrariescustomresource7AC4EEF3) Received response status [FAILED] from custom resource. Message returned: Exception thrown: Command '['/var/lang/bin/python3.10', '-m', 'pip', 'install', '--platform', 'manylinux2014_x86_64', '--only-binary=:all:', '-t', 'python', 'https://github.com/mlflow/mlflow-export-import/archive/refs/heads/master.zip']' returned non-zero exit status 1. (RequestId: f85047c2-d142-47c6-8c95-cb9bf0f11f89)
[17:53:15] Could not refresh notices: Error: getaddrinfo ENOTFOUND cli.cdk.dev-tools.aws.dev
❌  APP01-NVSGISRSSR36-DEVCDKAUTOMATIONENV failed: The stack named APP01-NVSGISRSSR36-DEVCDKAUTOMATIONENV failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Exception thrown: Command '['/var/lang/bin/python3.10', '-m', 'pip', 'install', '--platform', 'manylinux2014_x86_64', '--only-binary=:all:', '-t', 'python', 'https://github.com/mlflow/mlflow-export-import/archive/refs/heads/master.zip']' returned non-zero exit status 1. (RequestId: f85047c2-d142-47c6-8c95-cb9bf0f11f89)
[17:53:15] Error: ❌  APP01-NVSGISRSSR36-DEVCDKAUTOMATIONENV failed: The stack named APP01-NVSGISRSSR36-DEVCDKAUTOMATIONENV failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Exception thrown: Command '['/var/lang/bin/python3.10', '-m', 'pip', 'install', '--platform', 'manylinux2014_x86_64', '--only-binary=:all:', '-t', 'python', 'https://github.com/mlflow/mlflow-export-import/archive/refs/heads/master.zip']' returned non-zero exit status 1. (RequestId: f85047c2-d142-47c6-8c95-cb9bf0f11f89)
    at Object.deployStack2 [as deployStack] (/usr/lib/node_modules/aws-cdk/lib/index.js:573:7239)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/lib/node_modules/aws-cdk/lib/index.js:572:187958
[Pipeline] echo
===========================
[Pipeline] echo
>>>> CDK App Failed <<<<
[Pipeline] echo
===========================
[Pipeline] echo
hudson.AbortException: script returned exit code 1
[Pipeline] unstable
WARNING: CDK App failed hudson.AbortException: script returned exit code 1
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] } (Run Tests)
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: UNSTABLE

[Pipeline] unstable
WARNING: Downstream job FAILED
[Pipeline] sh
+ exit 1
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Run Tests)
Stage "Run Tests" skipped due to earlier failure(s)
[Pipeline] getContext
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
